service: soniqubeservice
frameworkVersion: "3"
plugins:
  - serverless-dotenv-plugin
  - serverless-prune-plugin
provider:
  name: aws
  vpc:
    securityGroupIds:
      - sg-018ab63bfcda5e4b4
    subnetIds:
      - subnet-0a563212177cac4a3
      # - subnet-05fcf1bd73f15f582
      # - subnet-01f5197e0807daff0
  runtime: nodejs14.x
  timeout: 30
  stage: dev
  region: ap-east-1
  deploymentBucket:
    name: www.soniqube.app
  apiGateway:
    binaryMediaTypes:
      - multipart/form-data
functions:
  graphql:
    handler: handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
custom:
  dotenv:
    exclude:
      - APOLLO_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
  prune:
    automatic: true
    number: 3
